# SourceHut Build Manifest
image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
    - nodejs
    - yarn
    - hut
environment:
    site: reaction-tester.lixquid.com
sources:
    - https://github.com/lixquid/app-reaction-tester
tasks:
    - build: |
          cd *
          yarn install
          yarn build
    - package: |
          cd */dist
          tar czvf ../dist.tgz *
          hut pages publish -d $site ../dist.tgz
